name: Build and deploy JAR app to Azure Web App - ecobins-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # Necesario para actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install
        working-directory: reciclaje-backend  # Ejecuta Maven en la carpeta del backend

      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp reciclaje-backend\target\reciclaje-backend-0.0.1-SNAPSHOT.jar deployment\
          cp reciclaje-backend\config.json deployment\
          cd deployment
          powershell.exe -command "Compress-Archive -Path * -DestinationPath ../deployment.zip"
          cd ..
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/deployment.zip'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Requerido para solicitar el JWT
      contents: read   # Requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_860D0ED4F4114F6AB311D4D08F84FD11 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C9F59E3A5B5A465FBC6113FA41BFDAF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62D4873725BD46AFADADDD77EAD3665F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecobins-backend'
          slot-name: 'Production'
          package: 'deployment.zip'
