name: Build and deploy JAR app to Azure Web App - ecotech-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Necesario para actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: |
          cd DAD/reciclaje-backend
          mvn clean install

      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp DAD/reciclaje-backend/target/reciclaje-backend-0.0.1-SNAPSHOT.jar deployment/
          cp DAD/reciclaje-backend/config.json deployment/
          cd deployment
          zip -r ../deployment.zip .  # Usamos zip para crear el paquete de despliegue
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/deployment.zip'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Requerido para solicitar el JWT
      contents: read   # Requerido para actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48E4E1E40E2240C3B3A0AFBC94FE6B36 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6BF7AC7056134CA6981A9C83077295EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5291DF4B076E469A8AF7992CD3C0A384 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecotech-backend'
          slot-name: 'Production'
          package: 'deployment.zip'
