name: Build and deploy Node.js app to Azure Web App - ecotech-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: reciclaje-frontend

    - name: Build project
      run: CI=false npm run build  # 🔹 Desactiva CI para evitar fallos por warnings
      working-directory: reciclaje-frontend

    - name: Debug list build folder
      run: ls -R
      working-directory: reciclaje-frontend/build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ecotech-frontend
        slot-name: Production
        package: reciclaje-frontend/build
        publish-profile: ${{ secrets.FRONTEND }}
