name: Build and deploy Node.js app to Azure Web App - ecotech-frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Esto es requerido para actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Ajusta esta ruta según sea necesario

      - name: Build project
        run: npm run build
        working-directory: ./frontend # Ajusta esta ruta según sea necesario

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: 'frontend/dist/' # Ajusta esta ruta según sea necesario

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecotech-frontend'
          slot-name: 'Production'
          package: 'frontend/dist/' # Ajusta esta ruta según sea necesario
          publish-profile: ${{ secrets.FRONTEND }}
